### ISSUE TITLE
Couldn't connect 

### ISSUE THREAD

**Issue by ItzTej8** [imchampagnepapi/TalkinchatPy#1]
Using python 3.9
Please provide requirements.txt    
---------------------------------------
**Log :** 

Traceback (most recent call last):
  File "/home/Minus8/tcBot/main.py", line 554, in <module>
    loop.run_until_complete(start_bot())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/Minus8/tcBot/main.py", line 520, in start_bot
websocket = await websockets.connect(SOCKET_URL, ssl=True)
  File "/home/Minus8/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/Minus8/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('49.12.166.219', 5333)

**Comment by imchampagnepapi** [comment]
Hello, Try now.

Running on MacOS Big Sur, **Python 3.10.0**

Let me know if the issue still persist, thanks.

![Screenshot 2022-01-14 at 1 44 50 AM](https://user-images.githubusercontent.com/74662905/149494599-54dae2c0-33fc-4c62-8f8a-98c2c4105cb8.png)
